MESSAGE_TIMESPAN = 2000
SIMULATED_DATA = False
I2C_ADDRESS = 0x77
#GPIO_PIN_ADDRESS = 17
CHANNEL_TEMPERATURE_HUMIDITY = 17
CHANNEL_SOIL_MOISTURE = 26 # HIGH = sufficient moisture, LOW = low moisture
CHANNEL_RAIN_SENSOR = 22 # HIGH = no rain, LOW = rain detected
CHANNEL_WATER_PUMP = 13
CHANNEL_DRAINAGE = 19
BLINK_TIMESPAN = 1000
CONNECTION_STRING = 'HostName=Caliber-IoTHub.azure-devices.net;DeviceId=raspberrypi3;SharedAccessKey=nK5Bep4DjcIZC7BXB+9ygnqr4Jq+04OE5IqJ2LwM/AM='
